# Project information
site_name: 笔记
site_url: https://xyxxxxx.github.io/note
site_author: xyx

# # Copyright
# copyright: Copyright &copy; 2016 - 2021 TensorStack

# Configuration
theme:
  name: material           # https://github.com/squidfunk/mkdocs-material
  custom_dir: overrides    # any file in 'overrides' directory will override the origin theme
                           # refer to https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme
  language: zh             # language
  features:
    - navigation.instant   # instant loading
                           # refer to https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    - navigation.indexes   # refer to https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
    # - navigation.sections  # optional
                           # refer to https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections
    - navigation.tabs      # enable navigation tabs, recommended for large docs with several parts
    - navigation.top       # add back-to-top button
    - search.highlight     # highlight all occurences of the search keyword
    - search.share         # allow to share current search query and result
    - search.suggest       # enable search to display completion suggestions (only worked for English)
  palette:                 # color scheme
    scheme: default        # 'default' for light mode, 'slate' for dark mode (not recommended)
    primary: teal          # primary color, used for header, sidebar, text links and several other components
    accent: light green    # accent color, used to denote elements that can be interacted with, e.g. hovered links, buttons and scrollbars
  # favicon: assets/icon.svg # favicon showed as tab icon, can be changed to user-provided image (*.png or *.svg)
  # logo: assets/logo.png    # logo showed at top left of page, can be changed to user-provided image (*.png or *.svg)

use_directory_urls: false  # prevent generating a directory for each markdown file when building

# Extensions
markdown_extensions:
  - admonition             # enable admonition
                           # refer to https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - attr_list              # enable Attribute List extension, which allows to add HTML attributes and CSS classes to Markdown elements
                           # refer to https://squidfunk.github.io/mkdocs-material/reference/buttons/
  - meta                   # enable metadata for md docs
  - pymdownx.arithmatex:   # enable Arithmatex extension, which allows rendering block and inline equations
      generic: true
  - pymdownx.caret         # optional, enable underline with double '^^', superscript with connected '^'
  - pymdownx.details       # make admonitions collapsible
  - pymdownx.emoji:        # optional, enable Emoji extension, which enables *.svg icons to be integrated inline
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      # options:             # add additional *.svg icons
      #   custom_icons:
      #     - overrides/.icons
  - pymdownx.highlight     # enable Highlight extension, which enables syntax highlight for code block
                           # refer to https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlight
  - pymdownx.inlinehilite  # enable InlineHilite extension, which enables syntax highlight for inline code
                           # refer to https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#inlinehilite
  - pymdownx.keys          # optional, enable keyboard key icon with double '++'
  - pymdownx.mark          # optional, enable mark with double '=='
  - pymdownx.superfences   # allow for nesting of code and content blocks inside admonitions
  - pymdownx.tabbed        # enable tabbed contents
                           # refet to https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - pymdownx.tilde         # optional, enable strikethrough with double '~~', subscript with connected '~'
  - toc:                   # Table of contents extension
      permalink: true      # add an anchor link at the end of each headline
      slugify: !!python/name:pymdownx.slugs.uslugify
                           # allow to slugify unicode title
      toc_depth: 4         # range of levels to be included in toc

# Plugins
plugins:
  - git-revision-date      # display date last updated at bottom of page for proofreading
                           # refer to https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=git+rev#revision-date
  - search                 # enable search

# Page Tree
nav:
  - 首页: index.html
  - 数学:
    - math/index.md
    - 代数:
      - math/algebra/index.md
      - 基础代数: math/algebra/elementary-algebra.md
      - 线性代数: math/algebra/linear-algebra.md
      - 线性代数理解: math/algebra/linear-algebra-understanding.md
      - 抽象代数: math/algebra/abstract-algebra.md
    - 分析:
      - math/analysis/index.md
      - 微积分: math/analysis/calculus.md
      - 多元微积分: math/analysis/multivariate-calculus.md
      - 矩阵微积分: math/analysis/matrix-calculus.md
      - 微分方程: math/analysis/differential-equation.md
      - 复分析: math/analysis/complex-analysis.md
      - 数学物理: math/analysis/mathematical-physics.md
    - 应用数学:
      - math/applied-mathematics/index.md
      - 数学优化:
        - math/applied-mathematics/optimization/index.md
        - 凸集: math/applied-mathematics/optimization/convex-set.md
        - 凸函数: math/applied-mathematics/optimization/convex-function.md
        - 凸优化: math/applied-mathematics/optimization/convex-optimization.md
        - 对偶性: math/applied-mathematics/optimization/duality.md
        - 非线性优化: math/applied-mathematics/optimization/nlp.md
      - 概率论:
        - math/applied-mathematics/probability-theory/index.md
        - 概率基础: math/applied-mathematics/probability-theory/probability-introduction.md
        - 随机变量: math/applied-mathematics/probability-theory/random-variable.md
        - 极限定理: math/applied-mathematics/probability-theory/limit-theorems.md
      - 统计学:
        - math/applied-mathematics/statistics/index.md
        - 基本概念: math/applied-mathematics/statistics/basic-concepts.md
        - 统计推断: math/applied-mathematics/statistics/statistical-inference.md
        - 假设检验: math/applied-mathematics/statistics/hypothesis-testing.md
        - 贝叶斯统计学: math/applied-mathematics/statistics/bayesian-statistics.md
      - 随机过程:
        - math/applied-mathematics/stochastic-process/index.md
        - 随机过程基础: math/applied-mathematics/stochastic-process/stochastic-process-introduction.md
        - 马尔可夫链: math/applied-mathematics/stochastic-process/markov-chain.md
        - 泊松过程: math/applied-mathematics/stochastic-process/poisson-process.md
    - 离散数学:
      - math/discrete-mathematics/index.md
      - 数学逻辑: math/discrete-mathematics/mathematical-logic.md
      - 集合论: math/discrete-mathematics/set-theory.md
      - 组合数学: math/discrete-mathematics/enumerative-combinatorics.md
      - 多项式: math/discrete-mathematics/polynomial.md
      - 图论: math/discrete-mathematics/graph-theory.md
      - 数论: math/discrete-mathematics/number-theory.md
  - 数据结构与算法:
    - 算法:
      - dsa/algorithm/index.md
      - 常见算法: dsa/algorithm/common-algorithm.md
      - 分而治之: dsa/algorithm/divide-and-conquer.md
      - 动态规划: dsa/algorithm/dynamic-programming.md
      - 贪心算法: dsa/algorithm/greedy-algorithm.md
      - 回溯法: dsa/algorithm/backtracking.md
      - 网络流算法: dsa/algorithm/network-flow-algorithm.md
      - 线性规划: dsa/algorithm/linear-programming.md
    - 数据结构:
      - dsa/data-structure/index.md
      - 数组，链表: dsa/data-structure/array-linked-list.md
      - 栈，队列: dsa/data-structure/stack-queue.md
      - 二叉搜索树: dsa/data-structure/binary-search-tree.md
      - 哈希表: dsa/data-structure/hash-table.md
      - 图: dsa/data-structure/graph.md
      - 堆: dsa/data-structure/heap.md
  - 网络:
    - net/index.md
    - 网络模型:
      - net/net-model/index.md
      - 传输层: net/net-model/transport-layer.md
      - 网络层: net/net-model/network-layer.md
      - 应用层: net/net-model/application-layer.md
  - Python:
    - python/index.md
    - 运行环境与开发工具: python/runtime-environment-devtool.md
    - 数据类型与操作: python/data-type-and-operation.md
    - 函数: python/function.md
    - 控制流: python/control-flow.md
    - 容器类型: python/container-type.md
    - 迭代器与生成器: python/iterator-and-generator.md
    - 面向对象编程: python/oop.md
    - IO: python/io.md
    - 进程与线程: python/process-and-thread.md
    - 错误处理与单元测试: python/error-handling-and-unit-test.md
    - 模块与包: python/module-and-package.md
    - 标准库: python/standard-library.md
    - 常用库: python/common-library.md
    - 风格指南: python/style-guide.md
  - 机器学习:
    - ml/index.md
    - 平台和工具:
      - ml/platform-and-tool/index.md
      - numpy: ml/platform-and-tool/numpy.md
      - pandas: ml/platform-and-tool/pandas.md
      - matplotlib: ml/platform-and-tool/matplotlib.md
      - PyTorch:
        - ml/platform-and-tool/pytorch/index.md
        - PyTorch: ml/platform-and-tool/pytorch/pytorch.md
        - torchvision: ml/platform-and-tool/pytorch/torchvision.md
        - torchserve: ml/platform-and-tool/pytorch/torchserve.md
        - "API: torch": ml/platform-and-tool/pytorch/api-torch.md
        - "API: torch.nn": ml/platform-and-tool/pytorch/api-nn.md
        - "API: torch.nn.functional": ml/platform-and-tool/pytorch/api-nn-functional.md
        - "API: torch.optim": ml/platform-and-tool/pytorch/api-optim.md
        - "API: torch.autograd": ml/platform-and-tool/pytorch/api-autograd.md
        - "API: torch.cuda": ml/platform-and-tool/pytorch/api-cuda.md
        - "API: torch.backends": ml/platform-and-tool/pytorch/api-backends.md
        - "API: torch.distributed": ml/platform-and-tool/pytorch/api-distributed.md
        - "API: torch.multiprocessing": ml/platform-and-tool/pytorch/api-multiprocessing.md
        - "API: torch.fft, torch.linalg, torch.special": ml/platform-and-tool/pytorch/api-math.md
        - "API: torch.random": ml/platform-and-tool/pytorch/api-random.md
        - "API: torch.sparse": ml/platform-and-tool/pytorch/api-sparse.md
        - "API: torch.utils.data": ml/platform-and-tool/pytorch/api-utils-data.md
        - "API: torch.utils.tensorboard": ml/platform-and-tool/pytorch/api-utils-tensorboard.md
        - Lightning: ml/platform-and-tool/pytorch/lightning.md
        - "API: lightning": ml/platform-and-tool/pytorch/api-lightning.md
  - 工具: 
    - tool/index.md
    - Linux 命令: tool/linux-command.md
    - Linux 工具: tool/linux-utility.md
    - Git: tool/git.md
  - 前端:
    - web/index.md
    - Simple HTML: web/simple-html.md
    - Simple CSS: web/simple-css.md


# Customization
# extra:
#   version:
#     provider: mike
#   social:                  # SNS links, for future use
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/tensorstack  # for example


# CSS Customization
extra_css:
  - stylesheets/extra.css

# JS Customization
extra_javascript:
  - javascripts/config.js  # MathJax configuration
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
