# Project information
site_name: 笔记
site_url: https://xyxxxxx.github.io/note
site_author: xyx

# # Copyright
# copyright: Copyright &copy; 2016 - 2021 TensorStack

# Configuration
theme:
  name: material           # https://github.com/squidfunk/mkdocs-material
  custom_dir: overrides    # any file in 'overrides' directory will override the origin theme
                           # refer to https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme
  language: zh             # language
  features:
    # - navigation.instant   # instant loading
                           # refer to https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    - navigation.indexes   # refer to https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
    # - navigation.sections  # optional
                           # refer to https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections
    - navigation.tabs      # enable navigation tabs, recommended for large docs with several parts
    - navigation.top       # add back-to-top button
    - search.highlight     # highlight all occurences of the search keyword
    - search.share         # allow to share current search query and result
    - search.suggest       # enable search to display completion suggestions (only worked for English)
  palette:                 # color scheme
    scheme: default        # 'default' for light mode, 'slate' for dark mode (not recommended)
    primary: teal          # primary color, used for header, sidebar, text links and several other components
    accent: light green    # accent color, used to denote elements that can be interacted with, e.g. hovered links, buttons and scrollbars
  # favicon: assets/icon.svg # favicon showed as tab icon, can be changed to user-provided image (*.png or *.svg)
  # logo: assets/logo.png    # logo showed at top left of page, can be changed to user-provided image (*.png or *.svg)

use_directory_urls: false  # prevent generating a directory for each markdown file when building

# Extensions
markdown_extensions:
  - admonition             # enable admonition
                           # refer to https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - attr_list              # enable Attribute List extension, which allows to add HTML attributes and CSS classes to Markdown elements
                           # refer to https://squidfunk.github.io/mkdocs-material/reference/buttons/
  - meta                   # enable metadata for md docs
  - pymdownx.arithmatex:   # enable Arithmatex extension, which allows rendering block and inline equations
      generic: true
  - pymdownx.caret         # optional, enable underline with double '^^', superscript with connected '^'
  - pymdownx.details       # make admonitions collapsible
  - pymdownx.emoji:        # optional, enable Emoji extension, which enables *.svg icons to be integrated inline
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      # options:             # add additional *.svg icons
      #   custom_icons:
      #     - overrides/.icons
  - pymdownx.highlight     # enable Highlight extension, which enables syntax highlight for code block
                           # refer to https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlight
  - pymdownx.inlinehilite  # enable InlineHilite extension, which enables syntax highlight for inline code
                           # refer to https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#inlinehilite
  - pymdownx.keys          # optional, enable keyboard key icon with double '++'
  - pymdownx.mark          # optional, enable mark with double '=='
  - pymdownx.superfences   # allow for nesting of code and content blocks inside admonitions
  - pymdownx.tabbed        # enable tabbed contents
                           # refet to https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - pymdownx.tilde         # optional, enable strikethrough with double '~~', subscript with connected '~'
  - toc:                   # Table of contents extension
      permalink: true      # add an anchor link at the end of each headline
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower      # allow to slugify unicode title
      toc_depth: 4         # range of levels to be included in toc

# Plugins
plugins:
  - git-revision-date      # display date last updated at bottom of page for proofreading
                           # refer to https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=git+rev#revision-date
  - search                 # enable search

# Page Tree
nav:
  - 首页: index.html
  - 数学:
    - math/index.md
    - 代数:
      - math/algebra/index.md
      - 基础代数: math/algebra/elementary-algebra.md
      - 线性代数: math/algebra/linear-algebra.md
      - 线性代数理解: math/algebra/linear-algebra-understanding.md
      - 抽象代数: math/algebra/abstract-algebra.md
    - 分析:
      - math/analysis/index.md
      - 微积分: math/analysis/calculus.md
      - 多元微积分: math/analysis/multivariate-calculus.md
      - 矩阵微积分: math/analysis/matrix-calculus.md
      - 微分方程: math/analysis/differential-equation.md
      - 复分析: math/analysis/complex-analysis.md
      - 数学物理: math/analysis/mathematical-physics.md
    - 应用数学:
      - math/applied-mathematics/index.md
      - 数学优化:
        - math/applied-mathematics/optimization/index.md
        - 凸集: math/applied-mathematics/optimization/convex-set.md
        - 凸函数: math/applied-mathematics/optimization/convex-function.md
        - 凸优化: math/applied-mathematics/optimization/convex-optimization.md
        - 对偶性: math/applied-mathematics/optimization/duality.md
        - 非线性优化: math/applied-mathematics/optimization/nlp.md
      - 概率论:
        - math/applied-mathematics/probability-theory/index.md
        - 事件的概率: math/applied-mathematics/probability-theory/probability-of-event.md
        - 随机变量: math/applied-mathematics/probability-theory/random-variable.md
        - 极限定理: math/applied-mathematics/probability-theory/limit-theorems.md
      - 统计学:
        - math/applied-mathematics/statistics/index.md
        - 基本概念: math/applied-mathematics/statistics/basic-concepts.md
        - 统计推断: math/applied-mathematics/statistics/statistical-inference.md
        - 假设检验: math/applied-mathematics/statistics/hypothesis-testing.md
        - 贝叶斯统计学: math/applied-mathematics/statistics/bayesian-statistics.md
      - 随机过程:
        - math/applied-mathematics/stochastic-process/index.md
        - 随机过程基础: math/applied-mathematics/stochastic-process/stochastic-process-introduction.md
        - 马尔可夫链: math/applied-mathematics/stochastic-process/markov-chain.md
        - 泊松过程: math/applied-mathematics/stochastic-process/poisson-process.md
    - 离散数学:
      - math/discrete-mathematics/index.md
      - 数学逻辑: math/discrete-mathematics/mathematical-logic.md
      - 集合论: math/discrete-mathematics/set-theory.md
      - 组合数学: math/discrete-mathematics/enumerative-combinatorics.md
      - 多项式: math/discrete-mathematics/polynomial.md
      - 图论: math/discrete-mathematics/graph-theory.md
      - 数论: math/discrete-mathematics/number-theory.md
  - CS:
    - 数据结构与算法:
      - 数据结构:
        - cs/dsa/data-structure/index.md
        - 数组和链表: cs/dsa/data-structure/array-and-linked-list.md
        - 栈和队列: cs/dsa/data-structure/stack-and-queue.md
        - 二叉搜索树: cs/dsa/data-structure/binary-search-tree.md
        - 哈希表: cs/dsa/data-structure/hash-table.md
        - 图: cs/dsa/data-structure/graph.md
        - 堆: cs/dsa/data-structure/heap.md
      - 算法:
        - cs/dsa/algorithm/index.md
        - 常见算法: cs/dsa/algorithm/common-algorithm.md
        - 分而治之: cs/dsa/algorithm/divide-and-conquer.md
        - 动态规划: cs/dsa/algorithm/dynamic-programming.md
        - 贪心算法: cs/dsa/algorithm/greedy-algorithm.md
        - 回溯法: cs/dsa/algorithm/backtracking.md
        - 网络流算法: cs/dsa/algorithm/network-flow-algorithm.md
        - 线性规划: cs/dsa/algorithm/linear-programming.md
      - Leetcode 例题: cs/dsa/leetcode-examples.md
    - 网络:
      - cs/net/index.md
      - 网络模型:
        - cs/net/net-model/index.md
        - 传输层: cs/net/net-model/transport-layer.md
        - 网络层: cs/net/net-model/network-layer.md
        - 应用层: cs/net/net-model/application-layer.md
    - 信息论:
      - cs/information-theory/index.md
      - 熵、相对熵与互信息: cs/information-theory/entropy.md
  - Python:
    - python/index.md
    - 运行环境与开发工具: python/runtime-environment-devtool.md
    - 数据类型与操作: python/data-type-and-operation.md
    - 函数: python/function.md
    - 控制流: python/control-flow.md
    - 容器类型: python/container-type.md
    - 迭代器与生成器: python/iterator-and-generator.md
    - 面向对象编程: python/oop.md
    - IO: python/io.md
    - 进程与线程: python/process-and-thread.md
    - 错误处理与单元测试: python/error-handling-and-unit-test.md
    - 模块与包: python/module-and-package.md
    - 标准库:
      - python/standard-library/index.md
      - "argparse——命令行选项、参数和子命令解析器": python/standard-library/argparse.md
      - "base64——Base16, Base32, Base64, Base85 数据编码": python/standard-library/base64.md
      - "builtins——内建对象": python/standard-library/builtins.md
      - "collections.abc——容器的抽象基类": python/standard-library/collections.abc.md
      - "collections——容器数据类型": python/standard-library/collections.md
      - "configparser——配置文件解析器": python/standard-library/configparser.md
      - "concurrent.futures——启动并行任务": python/standard-library/concurrent.futures.md
      - "copy——浅层和深层复制操作": python/standard-library/copy.md
      - "csv——CSV 文件读写": python/standard-library/csv.md
      - "datetime——基本日期和时间类型": python/standard-library/datetime.md
      - "enum——对枚举的支持": python/standard-library/enum.md
      - "内置函数": python/standard-library/functions.md
      - "functools——高阶函数和可调用对象上的操作": python/standard-library/functools.md
      - "glob——Unix 风格路径名模式扩展": python/standard-library/glob.md
      - "graphlib——操作类似图的结构的功能": python/standard-library/graphlib.md
      - "hashlib——安全哈希与消息摘要": python/standard-library/hashlib.md
      - "hmac——基于密钥的消息验证": python/standard-library/hmac.md
      - "importlib——import 的实现": python/standard-library/importlib.md
      - "inspect——检查对象": python/standard-library/inspect.md
      - "io——处理流的核心工具": python/standard-library/io.md
      - "itertools——为高效循环而创建迭代器的函数": python/standard-library/itertools.md
      - "json——JSON 编码和解码器": python/standard-library/json.md
      - "keyword——检验 Python 关键字": python/standard-library/keyword.md
      - "marshal——内部 Python 对象序列化": python/standard-library/marshal.md
      - "math——数学函数": python/standard-library/math.md
      - "multiprocessing——基于进程的并行": python/standard-library/multiprocessing.md
      - "operator——标准运算符替代函数": python/standard-library/operator.md
      - "os——多种操作系统接口": python/standard-library/os.md
      - "os.path——常用路径操作": python/standard-library/os.path.md
      - "pathlib——面向对象的文件系统路径": python/standard-library/pathlib.md
      - "pickle——Python 对象序列化": python/standard-library/pickle.md
      - "platform——获取底层平台的标识数据": python/standard-library/platform.md
      - "pprint——数据美化输出": python/standard-library/pprint.md
      - "queue——一个同步的队列类": python/standard-library/queue.md
      - "random——生成伪随机数": python/standard-library/random.md
      - "re——正则表达式操作": python/standard-library/re.md
      - "secrets——生成安全随机数字用于管理密码": python/standard-library/secrets.md
      - "select——等待 I/O 完成": python/standard-library/select.md
      - "shlex——简单的词法分析": python/standard-library/shlex.md
      - "shutil——高阶文件操作": python/standard-library/shutil.md
      - "signal——设置异步事件处理程序": python/standard-library/signal.md
      - "socket——底层网络接口": python/standard-library/socket.md
      - "subprocess——子进程管理": python/standard-library/subprocess.md
      - "sys——系统相关的参数和函数": python/standard-library/sys.md
      - "tarfile——读写 tar 归档文件": python/standard-library/tarfile.md
      - "tempfile——生成临时文件和目录": python/standard-library/tempfile.md
      - "threading——基于线程的并行": python/standard-library/threading.md
      - "time——时间的访问和转换": python/standard-library/time.md
      - "timeit——测量小段代码的执行时间": python/standard-library/timeit.md
      - "types——动态类型创建和内置类型名称": python/standard-library/types.md
      - "typing——类型提示支持": python/standard-library/typing.md
      - "urllib.parse——用于解析 URL": python/standard-library/urllib.parse.md
      - "urllib.request——用于打开 URL 的可扩展库": python/standard-library/urllib.request.md
      - "uuid——RFC 4122 定义的 UUID 对象": python/standard-library/uuid.md
      - "weakref——弱引用": python/standard-library/weakref.md
      - "zipfile——使用 ZIP 存档": python/standard-library/zipfile.md
    - 常用库:
      - python/common-library/index.md
      - "BeautifulSoup": python/common-library/beautifulsoup.md
      - "click": python/common-library/click.md
      - "filelock": python/common-library/filelock.md
      - "Pillow": python/common-library/pillow.md
      - "PyYAML (yaml)": python/common-library/pyyaml.md
      - "requests": python/common-library/requests.md
      - "rich": python/common-library/rich.md
      - "websocket-client (websocket)": python/common-library/websocket-client.md
    - 风格指南: python/style-guide.md
  - 机器学习:
    - ml/index.md
    - 统计学习:
      - 回归: ml/statistical-learning/regression.md
      - 朴素贝叶斯: ml/statistical-learning/nb.md
      - 感知器: ml/statistical-learning/perceptron.md
      - 支持向量机: ml/statistical-learning/svm.md
    - 深度学习:
      - 前馈神经网络（FNN）: ml/deep-learning/fnn.md
      - 卷积神经网络（CNN）: ml/deep-learning/cnn.md 
      - 循环神经网络（RNN）: ml/deep-learning/rnn.md
      - 嵌入: ml/deep-learning/embedding.md
      - 序列到序列模型: ml/deep-learning/seq2seq.md
      - Transformer: ml/deep-learning/transformer.md
      - 自监督学习模型: ml/deep-learning/self-supervised.md
      - 生成对抗网络（GAN）: ml/deep-learning/gan.md
      - 强化学习: ml/deep-learning/rl.md
      - 自动学习: ml/deep-learning/auto-learning.md
    - 常用技术:
      - 优化: ml/technique/optimization.md
      - 归一化: ml/technique/normalization.md
      - 泛化: ml/technique/generalization.md
      - 异常检测: ml/technique/anomaly-detection.md
      - 对抗攻击: ml/technique/adversarial-attack.md
      - 模型可解释性: ml/technique/explainable-ml.md
      - 迁移学习: ml/technique/transfer-learning.md
      - 模型压缩: ml/technique/model-compression.md
      - 终身学习: ml/technique/life-long-learning.md
    - 自然语言处理专题:
      - ml/nlp/index.md
      - 文本处理: ml/nlp/text-processing.md
      - 语言模型: ml/nlp/language-model.md
      - 朴素贝叶斯和情感分类: ml/nlp/sentiment-classification.md
      - 逻辑回归: ml/nlp/logistic-regression.md
      - 嵌入: ml/nlp/embedding.md
      - 神经网络: ml/nlp/neural-network.md
      - 词性标注和命名实体检测: ml/nlp/part-of-speech-tagging.md
    - 分布式训练:
      - ml/distributed/index.md
    - 平台和工具:
      - ml/platform-and-tool/index.md
      - NumPy: 
        - ml/platform-and-tool/numpy/index.md
        - 快速入门: ml/platform-and-tool/numpy/get-started.md
        - API: ml/platform-and-tool/numpy/api.md
      - pandas:
        - ml/platform-and-tool/pandas/index.md
        - 快速入门: ml/platform-and-tool/pandas/get-started.md
        - API: ml/platform-and-tool/pandas/api.md
      - matplotlib:
        - ml/platform-and-tool/matplotlib/index.md
        - 示例: ml/platform-and-tool/matplotlib/example.md
      - TensorFlow:
        - ml/platform-and-tool/tensorflow/index.md
        - TensorFlow: ml/platform-and-tool/tensorflow/tensorflow.md
        - "API: tf": ml/platform-and-tool/tensorflow/api-tf.md
        - "API: tf.config": ml/platform-and-tool/tensorflow/api-config.md
        - "API: tf.data": ml/platform-and-tool/tensorflow/api-data.md
        - "API: tf.distribute": ml/platform-and-tool/tensorflow/api-distribute.md
        - "API: tf.image": ml/platform-and-tool/tensorflow/api-image.md
        - "API: tf.keras": ml/platform-and-tool/tensorflow/api-keras.md
        - "API: tf.linalg": ml/platform-and-tool/tensorflow/api-linalg.md
        - "API: tf.math": ml/platform-and-tool/tensorflow/api-math.md
        - "API: tf.random": ml/platform-and-tool/tensorflow/api-random.md
        - "API: tf.signal": ml/platform-and-tool/tensorflow/api-signal.md
        - "API: tf.sparse": ml/platform-and-tool/tensorflow/api-sparse.md
        - "API: tf.strings": ml/platform-and-tool/tensorflow/api-strings.md
        - "API: tf.train": ml/platform-and-tool/tensorflow/api-train.md
        - "API: tfds": ml/platform-and-tool/tensorflow/api-tfds.md
      - PyTorch:
        - ml/platform-and-tool/pytorch/index.md
        - PyTorch: ml/platform-and-tool/pytorch/pytorch.md
        - torchvision: ml/platform-and-tool/pytorch/torchvision.md
        - torchserve: ml/platform-and-tool/pytorch/torchserve.md
        - "API: torch": ml/platform-and-tool/pytorch/api-torch.md
        - "API: torch.nn": ml/platform-and-tool/pytorch/api-nn.md
        - "API: torch.nn.functional": ml/platform-and-tool/pytorch/api-nn-functional.md
        - "API: torch.optim": ml/platform-and-tool/pytorch/api-optim.md
        - "API: torch.autograd": ml/platform-and-tool/pytorch/api-autograd.md
        - "API: torch.cuda": ml/platform-and-tool/pytorch/api-cuda.md
        - "API: torch.backends": ml/platform-and-tool/pytorch/api-backends.md
        - "API: torch.distributed": ml/platform-and-tool/pytorch/api-distributed.md
        - "API: torch.multiprocessing": ml/platform-and-tool/pytorch/api-multiprocessing.md
        - "API: torch.fft, torch.linalg, torch.special": ml/platform-and-tool/pytorch/api-math.md
        - "API: torch.sparse": ml/platform-and-tool/pytorch/api-sparse.md
        - "API: torch.utils.data": ml/platform-and-tool/pytorch/api-utils-data.md
        - "API: torch.utils.tensorboard": ml/platform-and-tool/pytorch/api-utils-tensorboard.md
        - Lightning: ml/platform-and-tool/pytorch/lightning.md
        - "API: lightning": ml/platform-and-tool/pytorch/api-lightning.md
      - horovod: ml/platform-and-tool/horovod.md
      - nni:
        - ml/platform-and-tool/nni/index.md
        - 调参器: ml/platform-and-tool/nni/tuner.md
  - 参考和工具:
    - Linux:
      - Linux 命令: reference-and-tool/linux/linux-command.md
      - Linux 命令行工具: reference-and-tool/linux/linux-command-line-tool.md
    - 文件格式:
      - json: reference-and-tool/file-format/json.md
      - yaml: reference-and-tool/file-format/yaml.md
      - xml: reference-and-tool/file-format/xml.md
      - markdown: reference-and-tool/file-format/markdown.md
    - 编码:
      - 字符集和字符编码: reference-and-tool/encoding/charset-and-encoding.md
      - Base64: reference-and-tool/encoding/base64.md
    # - 包管理工具:
    - 文本工具:
      - 正则表达式: reference-and-tool/text-tool/regular-expression.md
      - Vim: reference-and-tool/text-tool/vim.md
    - 构建工具:
      - make: reference-and-tool/build-tool/make.md
    - Git: reference-and-tool/git.md
    - 词汇表: reference-and-tool/vocabulary.md
  - 前端:
    - Simple HTML: web/simple-html.md
    - Simple CSS: web/simple-css.md


# Customization
# extra:
#   version:
#     provider: mike
#   social:                  # SNS links, for future use
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/tensorstack  # for example


# CSS Customization
extra_css:
  - stylesheets/extra.css

# JS Customization
extra_javascript:
  - javascripts/mathjax.js  # MathJax configuration
  - javascripts/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.cs/net/npm/mathjax@3/es5/tex-mml-chtml.js
